---
# tasks file for sysfsutils

- block:
    - name: install sysfsutils
      apt:
        name: sysfsutils
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
        state: latest
        update_cache: yes

  become: yes
  become_method: sudo
  tags:
    - sysfsutils
